name: ETL CI + Deploy to Azure Function

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ETL_AZURE_CREDENTIALS }}

      - name: Deploy ETL to Staging slot
        uses: azure/functions-action@v1
        with:
          app-name: etl-azure-func
          slot-name: staging
          package: ./etl

      # Optional: run integration tests or health checks against staging
      - name: Validate staging deployment
        run: |
          curl -f https://etl-azure-func-staging.azurewebsites.net/api/health || exit 1

      - name: Swap Staging -> Production
        run: |
          az functionapp deployment slot swap \
            --name etl-azure-func \
            --resource-group GitHub-Rg \
            --slot staging \
            --target-slot production
